name: Maven Build

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'

    - name: Build with Maven
      run: mvn clean install

    - name: check the arti
      run: ls -la target

    - name: copy arti into root dir 
      run: cp target/maven-simple-0.2-SNAPSHOT.jar docker/logger.jar

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
       
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ahmedsherifmo
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile  # Update this with the path to your Dockerfile
        push: true
        tags: ahmedsherifmo/mvn-loggging:latest 